### ISSUE TITLE
Wrap exceptions from `DB:Pool`

### ISSUE THREAD

**Issue by syeopite** [jgaskins/http_client#1]
Hello,

It'll be nice if exceptions from DB:Pool can be wrapped within this shard as to make it clearer the source of an error is from the HTTP client pool.

In a large application, there may need to be a database connection which will also use `DB:Pool` to pool together database connections in addition to a HTTP pool meaning that the two would both raise errors from the `DB` shard which can get confusing for debugging.

**Comment by jgaskins** [comment]
Good idea. I haven't run into this yet but there are some great reasons to disambiguate that here.

**Comment by jgaskins** [comment]
Fixed in 958cf56.
